services:
  postgres:
    image: postgres:16
    container_name: gmaps_scraper_postgres
    environment:
      POSTGRES_DB: gmaps_scraper
      POSTGRES_USER: gmaps_user
      POSTGRES_PASSWORD: gmaps_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gmaps_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: gmaps_scraper_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      target: development
    container_name: gmaps_scraper_api
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn gmaps_scraper_server.main_api:app --host 0.0.0.0 --port 8001 --reload

volumes:
  postgres_data:
